engine: cpu
paths:
  db_host_windows: ./clark_db
  data_host_windows: ./fastQ_reads
sample: SRR7497167_1
clark:
  image: quay.io/biocontainers/clark:1.2.6.1--h4ac6f70_3
  threads: 8
  kmer_length: 27
  sampling_factor: 2
jetson_nano:
  host: 100.71.242.74
  remote_db: /home/pathogen/cuclark_db
  remote_workspace: /home/pathogen/pathogenius_ws
  cuclark_dir: /home/pathogen/cuclark
  user: pathogen
  ssh_batch_mode: true
genome_sources:
  - path: ./clark_db
  - path: C:\Users\yalid\Desktop\Pathogenius2\genomes
    reads_mapping: C:\Users\yalid\Desktop\Pathogenius2\reads_mapping.tsv\reads_mapping.tsv
