paths:
  # Everything is now inside your WSL home directory
  db_host: "/home/yalid/my_pathogen_db"
  data_wsl: "/home/yalid/fastq"
  results_wsl: "/home/yalid/results/kraken2"

kraken2:
  threads: 8
  confidence: 0.1